version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
      # Optional: For trust authentication (development only)
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  app:
    image: python:3.9-slim
    command: uvicorn app:app --reload
    volumes:
      - ./:/code
    ports:
      - "8000:8000"