[project.dependencies]
fastapi = "0.68.0"
uvicorn = "0.15.0"
sqlalchemy = "1.4.46"
python-dotenv = "0.19.0"
passlib = "1.7.3"
jose = "2.0.0"
yandex-oauth = "0.2.5"
aiofiles = "0.8.0"
psycopg2-binary = "2.9.10"