version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key
      - YANDEX_CLIENT_ID=your-client-id
      - YANDEX_CLIENT_SECRET=your-client-secret
      - YANDEX_REDIRECT_URI=http://localhost:8000/auth/yandex/callback